/*
 * index.js
 *
 * part of FreeSense WebUI (https://www.freesense.org)
 * Copyright (c) 2026 The FreeSense Project
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * @freesense/ui runtime entry. Bundled by esbuild into dist/public/ui/fs-ui.js.
 *
 * Exposes window.FS (and jQuery as window.$ / window.jQuery for element code
 * and package plugins). Elements register themselves with FS.el.define() from
 * their own modules (packages/ui/elements/<name>/<name>.js), imported below
 * as they are added to the catalogue.
 */
import $ from 'jquery';
import * as bootstrap from 'bootstrap';
import { api } from './api.js';
import { batch } from './batch.js';
import { live } from './live.js';
import { el } from './el.js';
import { theme } from './theme.js';
import { fmt } from './fmt.js';
import { nav } from './nav.js';
import { states } from './states.js';
import { i18n } from './i18n.js';

/* Every element in packages/ui/elements/ (index generated by the build). */
import 'fs-elements';

const pkg = { version: __FS_UI_VERSION__, themeScheme: __FS_THEME_SCHEME__ };

const FS = { version: pkg.version, themeScheme: pkg.themeScheme, api, batch, live, el, theme, fmt, nav, states, i18n, bootstrap };

window.$ = window.jQuery = $;
window.bootstrap = bootstrap;
window.FS = FS;

$(() => el.start());

export default FS;
